FROM kalilinux/kali-rolling
LABEL org.opencontainers.image.authors="githubfoam"

#clean start
RUN apt-get update -y && apt-get upgrade -y && apt-get autoremove - && apt-get clean

#packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    aircrack-ng \
    ncat  \
    hping3

#testing
RUN hping3 -v

WORKDIR /home/ansible