FROM kalilinux/kali-rolling
LABEL org.opencontainers.image.authors="githubfoam"


#clean start
RUN apt-get update -y && apt-get upgrade -y && apt-get autoremove - && apt-get clean 


#packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    aircrack-ng \
    ncat  \
    hping3

# https://www.kali.org/docs/containers/using-kali-docker-images/
# https://www.kali.org/docs/containers/official-kalilinux-docker-images/
#testing
RUN hping3 -v

